# Test your FastAPI endpoints
GET http://127.0.0.1:8000/
Accept: application/json
###


POST http://127.0.0.1:8000/api/v1/task/?_
Accept: application/json
###

DELETE http://127.0.0.1:8000/api/v1/task/1
Accept: application/json
###

PATCH http://127.0.0.1:8000/api/v1/task/1
Accept: application/json